[tool.poetry]
name = "evalio"
version = "0.1.0"
description = ""
authors = ["'Gilad Barnea' <gilad.b@pecan.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
